"""Core types and deterministic baseline for ClinicalMatcher."""

from .models import (
    AtomicCondition,
    AtomicDecision,
    ComparisonOperator,
    ConditionExpression,
    Criterion,
    CriterionDecision,
    CriterionType,
    Decision,
    Evidence,
    ExpressionType,
    Fact,
    FactSelection,
    Patient,
    TimeDirection,
    TimeWindow,
    Trial,
    TrialMatch,
    TruthValue,
    TypedValue,
    ValueType,
)
from .pipeline import evaluate_criterion, match_patient

__all__ = [
    "AtomicCondition",
    "AtomicDecision",
    "ComparisonOperator",
    "ConditionExpression",
    "Criterion",
    "CriterionDecision",
    "CriterionType",
    "Decision",
    "Evidence",
    "ExpressionType",
    "Fact",
    "FactSelection",
    "Patient",
    "TimeDirection",
    "TimeWindow",
    "Trial",
    "TrialMatch",
    "TruthValue",
    "TypedValue",
    "ValueType",
    "evaluate_criterion",
    "match_patient",
]
